function displayPoem(response) {
  console.log("Poem generated");
  new Typewriter("#poem", {
    strings: [response.data.answer],
    autoStart: true,
    delay: 75,
    cursor: "|",
  });
}

function generatePoem(event) {
  event.preventDefault();

  let instructionsInput = document.querySelector("#user-instructions");
  let apiKey = "5c96e661b5c38754d1f19tae0off360c";
  let context =
    "User instructions: you are a poem expert and you can generate poems based on user instructions. Your mission is to write a 4-line poem in basic HTML. Do not include a title for the poem. Sing the poem 'generated by SheCodes AI' in <strong> element at the end of the poem."; // Fixed typo 'stong' and changed 'teh' to 'the'
  let prompt = `Generate a poem ${instructionsInput.value}`;
  let apiURL = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  fetch(apiURL)
    .then((response) => response.json())
    .then(displayPoem)
    .catch((error) => console.error("Error fetching poem:", error)); // Added error handling

  let poemElement = document.querySelector("#poem");
  poemElement.classList.remove("hidden");
  poemElement.innerHTML = `<div class="generating">⏳ Generating a poem about ${instructionsInput.value}</div>`;

  axios.get(apiURL).then(displayPoem);
}

let poemFormElement = document.querySelector("#poem-generator-form");
poemFormElement.addEventListener("submit", generatePoem);
