function displayPoem(response) {
  console.log("poem generated");
  new Typewriter("#poem", {
    strings: response.data.answer,
    autoStart: true,
    delay: 1,
    cursor: "|",
  });
}

function generatePoem(event) {
  event.preventDefault();
  let instructionsInput = document.querySelector("#user-instructions");
  let apiKey = "5c96e661b5c38754d1f19tae0off360c";
  let prompt = `Generate a poem ${instructionsInput.value}`;
  let context =
    "User instructions: you are a poem expert and you can generate poems based on user instructions. Your mission is to write a 4 line poem in basic HTML. Do not include a title for the poem. sing the poem 'generated by SheCodes AI'in <stong> element at teh end of the poem";
  let apiURL = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  console.log("Generating poem");
  console.log(`Prompt: ${prompt}`);
  console.log(`Context: ${context}`);
  axios.get(apiURL).then(displayPoem);
}

let poemFormElement = document.querySelector("#poem-generator-form");
poemFormElement.addEventListener("submit", generatePoem);
